### ISSUE TITLE
Add set-up / local dev instructions

### ISSUE THREAD

**Issue by rowan-m** [GoogleChromeLabs/form-troubleshooter#1]
A quick section in the README to go to `chrome://extensions`, enable "Developer Mode", and then "Load unpacked" at the top-level directory would help.

**Comment by samdutton** [comment]
Good idea! I've added [installation](https://github.com/GoogleChromeLabs/form-troubleshooter/blob/main/README.md#installation) and [usage](https://github.com/GoogleChromeLabs/form-troubleshooter/blob/main/README.md#usage) sections.
