### ISSUE TITLE
Add support web components that use the shadow DOM

### ISSUE THREAD

**Issue by socsieng** [GoogleChromeLabs/form-troubleshooter#13]
Web pages built using web components that use the shadow DOM are not being correctly audited.

Example: https://paydemo.withgoogle.com/checkout

![image](https://user-images.githubusercontent.com/2647062/126681038-6ca557e1-d7b8-4554-b8f1-16f73cc57844.png)

The extension should also traverse the shadow DOM tree to identify form fields.

**Comment by samdutton** [comment]
Ah — yes. I'd noticed this...
