### ISSUE TITLE
Strictness of invalid/unrecognized input attributes

### ISSUE THREAD

**Issue by socsieng** [GoogleChromeLabs/form-troubleshooter#2]
I ran the extension against https://payments-react-store.web.app/checkout with `chrome://flags/#show-autofill-type-predictions` enabled and received the following:

![image](https://user-images.githubusercontent.com/2647062/126397842-a431f8eb-383d-4587-bad3-dd8b2672724b.png)

Developers who are building/testing forms may have this flag enabled. Should `autofill-information` and `autofill-prediction` be added to the allowed list of attributes?

Also, what is the expectation around reporting issues and their severity? Should warnings be actionable?

**Comment by samdutton** [comment]
Good idea — [added](https://github.com/GoogleChromeLabs/form-troubleshooter/commit/623c064ffa2a249b39b2c7a02034b23cdd458dce#diff-ff5df2adad8de63e9192155f81c59b298fae7fbf4b3fcc8b370689aab90b4472).

**Comment by samdutton** [comment]
> Also, what is the expectation around reporting issues and their severity? Should warnings be actionable?

I think both warnings and errors should be actionable. To be honest, I think it's hard to formalise (or be precise about) the difference between warnings and errors, except that errors are issues that appear 'definitely/always wrong': a label with a `for` attribute that doesn't match any form field, an empty `for` attribute, etc.
