### ISSUE TITLE
Add a score indicating how well the form follows guidance

### ISSUE THREAD

**Issue by socsieng** [GoogleChromeLabs/form-troubleshooter#21]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. For example: I'm always frustrated when [...]

Include a score in the extension popup so that users can quickly assess how well their forms adhere to guidance and determine what (if any) action should be taken to remediate.

This score may be more useful for non-developers to take back to their development teams.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

Add a score that summarizes the audit findings. Possibly something like an A to F scale, or 0 to 100% score. Ideally this would be consistent with how browsers evaluate Autofill confidence.

Example: https://www.figma.com/file/8aClB2ZylfcCqy0OhWn5GS/Form-troubleshooter-proposal

![image](https://user-images.githubusercontent.com/2647062/128060625-1f7e76e2-7350-4e44-9a5b-ac9a47fb0584.png)

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

None

**Additional context** Add any other context or screenshots about the feature request here.

None

**Comment by samdutton** [comment]
Hmm... Tempting. A great incentive, but tricky to get right (as with Lighthouse).
