### ISSUE TITLE
Investigate why form fields aren't being highlighted

### ISSUE THREAD

**Issue by socsieng** [GoogleChromeLabs/form-troubleshooter#43]
Form fields aren't being highlighted when hovering/clicking on element links at the following site: https://www.meandem.com/e-gift-card

The text fields scroll into view which means that there isn't a problem with identifying the element, but may be related to CSS specificity.

**Comment by socsieng** [comment]
Elements are now being highlighted, however, they aren't appearing in the correct position.

Example:
![image](https://user-images.githubusercontent.com/2647062/129940844-82fde971-c426-4c0b-a962-a270ddec2999.png)

Possibly related to elements with `position: fixed`

**Comment by samdutton** [comment]
Confirmed issue as described.
